/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Selection = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'odds' : IDL.Float64,
});
export const Status = IDL.Variant({
  'closed' : IDL.Null,
  'upcoming' : IDL.Null,
  'settled' : IDL.Null,
  'live' : IDL.Null,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : Time,
  'status' : Status,
  'title' : IDL.Text,
  'winningSelection' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
  'sport' : IDL.Text,
  'selections' : IDL.Vec(Selection),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const UserAccount = IDL.Record({
  'balance' : IDL.Float64,
  'user' : IDL.Principal,
  'totalWagered' : IDL.Float64,
  'totalLost' : IDL.Float64,
  'totalWon' : IDL.Float64,
});
export const Status__1 = IDL.Variant({
  'won' : IDL.Null,
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'lost' : IDL.Null,
});
export const Bet = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status__1,
  'eventId' : IDL.Nat,
  'user' : IDL.Principal,
  'stake' : IDL.Float64,
  'selectionId' : IDL.Nat,
  'potentialPayout' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelEvent' : IDL.Func([IDL.Nat], [], []),
  'createEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Time, IDL.Vec(Selection)],
      [IDL.Nat],
      [],
    ),
  'depositCredits' : IDL.Func([IDL.Float64], [IDL.Float64], []),
  'getActiveMarkets' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEvent' : IDL.Func([IDL.Nat], [Event], ['query']),
  'getMyAccountSummary' : IDL.Func([], [UserAccount], ['query']),
  'getMyBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getMyBets' : IDL.Func([], [IDL.Vec(Bet)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginAccount' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'placeBet' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Float64], [IDL.Nat], []),
  'registerAccount' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'settleEvent' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateEventStatus' : IDL.Func([IDL.Nat, Status], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Selection = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'odds' : IDL.Float64,
  });
  const Status = IDL.Variant({
    'closed' : IDL.Null,
    'upcoming' : IDL.Null,
    'settled' : IDL.Null,
    'live' : IDL.Null,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : Time,
    'status' : Status,
    'title' : IDL.Text,
    'winningSelection' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
    'sport' : IDL.Text,
    'selections' : IDL.Vec(Selection),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const UserAccount = IDL.Record({
    'balance' : IDL.Float64,
    'user' : IDL.Principal,
    'totalWagered' : IDL.Float64,
    'totalLost' : IDL.Float64,
    'totalWon' : IDL.Float64,
  });
  const Status__1 = IDL.Variant({
    'won' : IDL.Null,
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'lost' : IDL.Null,
  });
  const Bet = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status__1,
    'eventId' : IDL.Nat,
    'user' : IDL.Principal,
    'stake' : IDL.Float64,
    'selectionId' : IDL.Nat,
    'potentialPayout' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelEvent' : IDL.Func([IDL.Nat], [], []),
    'createEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Time, IDL.Vec(Selection)],
        [IDL.Nat],
        [],
      ),
    'depositCredits' : IDL.Func([IDL.Float64], [IDL.Float64], []),
    'getActiveMarkets' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEvent' : IDL.Func([IDL.Nat], [Event], ['query']),
    'getMyAccountSummary' : IDL.Func([], [UserAccount], ['query']),
    'getMyBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getMyBets' : IDL.Func([], [IDL.Vec(Bet)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginAccount' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'placeBet' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Float64], [IDL.Nat], []),
    'registerAccount' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'settleEvent' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateEventStatus' : IDL.Func([IDL.Nat, Status], [], []),
  });
};

export const init = ({ IDL }) => { return []; };