/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bet {
  'id' : bigint,
  'status' : Status__1,
  'eventId' : bigint,
  'user' : Principal,
  'stake' : number,
  'selectionId' : bigint,
  'potentialPayout' : number,
}
export interface Event {
  'id' : bigint,
  'startTime' : Time,
  'status' : Status,
  'title' : string,
  'winningSelection' : [] | [bigint],
  'description' : string,
  'sport' : string,
  'selections' : Array<Selection>,
}
export interface Selection { 'id' : bigint, 'name' : string, 'odds' : number }
export type Status = { 'closed' : null } |
  { 'upcoming' : null } |
  { 'settled' : null } |
  { 'live' : null };
export type Status__1 = { 'won' : null } |
  { 'active' : null } |
  { 'cancelled' : null } |
  { 'lost' : null };
export type Time = bigint;
export interface UserAccount {
  'balance' : number,
  'user' : Principal,
  'totalWagered' : number,
  'totalLost' : number,
  'totalWon' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelEvent' : ActorMethod<[bigint], undefined>,
  'createEvent' : ActorMethod<
    [string, string, string, Time, Array<Selection>],
    bigint
  >,
  'depositCredits' : ActorMethod<[number], number>,
  'getActiveMarkets' : ActorMethod<[], Array<Event>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEvent' : ActorMethod<[bigint], Event>,
  'getMyAccountSummary' : ActorMethod<[], UserAccount>,
  'getMyBalance' : ActorMethod<[], number>,
  'getMyBets' : ActorMethod<[], Array<Bet>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginAccount' : ActorMethod<[string, string], string>,
  'placeBet' : ActorMethod<[bigint, bigint, number], bigint>,
  'registerAccount' : ActorMethod<
    [string, string, string, string, string],
    string
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'settleEvent' : ActorMethod<[bigint, bigint], undefined>,
  'updateEventStatus' : ActorMethod<[bigint, Status], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];